"""add deck context to conversations

Revision ID: 08b9a4e35aeb
Revises: 99c51a8262a9
Create Date: 2026-05-06 17:32:59.523972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b9a4e35aeb'
down_revision: Union[str, Sequence[str], None] = '99c51a8262a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('format', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('commander_name', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('signature_spell', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'signature_spell')
    op.drop_column('conversations', 'commander_name')
    op.drop_column('conversations', 'format')
    # ### end Alembic commands ###
